contestants:
  - "Aisha"
  - "April"
  - "Brett"
  - "Charleine"
  - "Dan"
  - "David"
  - "Elle"
  - "Gary"
  - "Jenny"
  - "Joseph"
  - "Mergim"
  - "Natalie"
  - "Richard"
  - "Ruth"
  - "Sam"
  - "Scott"
  - "Selina"
  - "Vana"

interviews:
  - "I'm the best me I can be."
  - "I've come from nothing."
  - "I didn't need no education."
  - "I'm in this to win."
  - "Are you a one trick pony?"
  - "You're not listening to me!"
  - "The bottom line is [...]"
  - "I'm a born leader!"
  - "This was a disastrous interview."
  - "X is full of bullshit!"
  - "It's so unfair!"
  - "It says here on your CV [...]"
  - "Please let me finish."
  - "You're interrupting me!"
  - "I'm not a passenger."
  - "The gloves are coming off."
  - "You've got to man-up!"
  - "I mean business."
  - "The sky's the limit."
  - "I'm exactly what it says on the tin"
  - "CAN I JUST SAY..."
  - "LOOK [...]"
  - "I don't want to hear from you any more/I'm fed up with hearing you."
  - "Shambles!"
  - "110\%"
  - "At the end of the day"
  - "Karen calls upon someones bullshit"
  - "Running to phone in PJs"
  - "A reference to a tough upbringing"
  - "Lord Sugar makes a terrible terrible joke"
  - "Fog happens to coincide with early morning minivans-driving-away-from-house shot"
  - "Blatant discrepancy between fired candidate's clothing with departing taxi shots"
  - "Candidate uses the third person"
  - "Someone forgets to call Alan Sugar a lord"
  - "Lord Sugar gets angry because someone forgets to call him a Lord"
  - "Lord Sugar arrives unannounced into the house"
  - "Lord Sugar talking from really far away in a building"
  - "Lord Sugar talking from so far away they've had to put him on a monitor"
  - "Candidate has a breakdown and admits they aren't Superman"
  - "Candidate compares self to Lord Sugar"
  - "Candidate cries"
  - "Candidate states that the day is the worst of their life"
  - "Rather you than me"
  - "Candidate makes impossible promise that interviewer calls on"
  - "Interviewer insults candidate's background"



tasks:
  - "I'm the best me I can be."
  - "I've come from nothing."
  - "I didn't need no education."
  - "Let me take charge."
  - "I could have done a better job but didn't volunteer myself."
  - "I do this in my day job."
  - "I deserve to be project manager."
  - "I'm in this to win."
  - "This is the last time I want to see you here in the [elimination round]."
  - "Are you a one trick pony?"
  - "You're not listening to me!"
  - "Failure is not an option."
  - "I knew we should've gone with my gut instead."
  - "The bottom line is [...]"
  - "I'm a born leader!"
  - "This was a disastrous task."
  - "X is full of bullshit!"
  - "Lord Sugar questioning his need for salesmen"
  - "It's so unfair!"
  - "It says here on your CV [...]"
  - "WHAT WENT WRONG!?!?!?!"
  - "Please let me finish."
  - "I've got a girlfriend/boyfriend."
  - "You're interrupting me!"
  - "I'm not a passenger."
  - "CLAUDE tells me [...]"
  - "The gloves are coming off."
  - "You've got to man-up!"
  - "You lost us this task."
  - "A load of toot."
  - "I mean business."
  - "Lean mean selling machine."
  - "The sky's the limit."
  - "I'm exactly what it says on the tin"
  - "You lost us the task"
  - "Just give me one more chance"
  - "CAN I JUST SAY..."
  - "LOOK [...]"
  - "I'm an expert at this trust me it's my background"
  - "They can't make a decision"
  - "I can't lose in this task"
  - "X feels threatened by me."
  - "I don't want to hear from you any more/I'm fed up with hearing you."
  - "I take responsibility"
  - "I'm going to give you the benefit of the doubt."
  - "Shambles!"
  - "110\%"
  - "At the end of the day"
  - "We're running behind"
  - "X (and Y) let the team down"
  - "Trust me"
  - "The task is a nightmare"
  - "I don't deserve to be here"
  - "Music ripped off from another BBC TV series"
  - "Slow batting of eyelashes"
  - "Candidate admits failure is their fault"
  - "Candidate insists they could make a lot of money with Lord Sugar"
  - "Sexist sales technique"
  - "Karen is bewildered by a candidate"
  - "Candidates stereotype potential customers"
  - "Team fails to meet goal/deadline"
  - "Sale falls through because other team members keeps interrupting"
  - "Flirty sales patter after a sale has already been made"
  - "Karen raises eyebrow"
  - "Karen rolls eyes"
  - "Karen calls upon someones bullshit"
  - "Task-based pun"
  - "Running to phone in PJs"
  - "Claude scowls at someone"
  - "Claude insults candidate or their ideas"
  - "Flirty sales patter fails"
  - "Candidates become romantically involved"
  - "A reference to a tough upbringing"
  - "Lord Sugar gets annoyed about people losing him money"
  - "The prize for winning a task involves going in a helicopter"
  - "People have to run because they have a stupid deadline"
  - "Lord Sugar makes a terrible terrible joke"
  - "DOUBLE FIRING"
  - "Fog happens to coincide with early morning minivans-driving-away-from-house shot"
  - "Obvious product placement despite the BBC"
  - "Blatant discrepancy between fired candidate's clothing with departing taxi shots"
  - "Candidate uses the third person"
  - "Someone forgets to call Alan Sugar a lord"
  - "Lord Sugar gets angry because someone forgets to call him a Lord"
  - "A candidate chases someone down the street to sell them something"
  - "Lord Sugar arrives unannounced into the house"
  - "Someone cancels a telephone call in the middle of a conversation"
  - "Lord Sugar talking from really far away in a building"
  - "Lord Sugar talking from so far away they've had to put him on a monitor"
  - "Project Manager drank the Kool-Aid and now fanatically believes in \#TEAM :'D"
  - "Project Manager has a breakdown and admits they aren't Superman"
  - "Awkward moment when candidates at the house slag off the person who just returned"
  - "Candidate compares self to Lord Sugar"


